// Objective-C API for talking to github.com/Dreamacro/clash Go package.
//   gobind -lang=objc github.com/Dreamacro/clash
//
// File is generated by gobind. Do not edit.

#ifndef __Clash_H__
#define __Clash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void ClashRun(void);

FOUNDATION_EXPORT void ClashSetDir(NSString* _Nullable path);

#endif
